//toggle-nav
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
//login
export const LOGIN = "LOGIN";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
//register
export const REGISTER = "REGISTER";
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
//publish
export const PUBLISH = "PUBLISH";
export const PUBLISH_REQUEST = "PUBLISH_REQUEST";
export const PUBLISH_SUCCESS = 'PUBLISH_SUCCESS';
export const PUBLISH_FAILURE = "PUBLISH_FAILURE";
//article lists
export const ARTICLE_LIST_GET = "ARTICLE_LIST_GET";
export const ARTICLE_LIST_GET_REQUEST = "ARTICLE_LIST_GET_REQUEST";
export const ARTICLE_LIST_GET_SUCCESS = 'ARTICLE_LIST_GET_SUCCESS';
export const ARTICLE_LIST_GET_FAILURE = "ARTICLE_LIST_GET_FAILURE";
//article delete
export const ARTICLE_DELETE = "ARTICLE_DELETE";
export const ARTICLE_DELETE_REQUEST = "ARTICLE_DELETE_REQUEST";
export const ARTICLE_DELETE_SUCCESS = 'ARTICLE_DELETE_SUCCESS';
export const ARTICLE_DELETE_FAILURE = "ARTICLE_DELETE_FAILURE";
//article detail
export const ARTICLE_GET_ID = "ARTICLE_GET_ID";
export const ARTICLE_GET_ID_REQUEST = "ARTICLE_GET_ID_REQUEST";
export const ARTICLE_GET_ID_SUCCESS = 'ARTICLE_GET_ID_SUCCESS';
export const ARTICLE_GET_ID_FAILURE = "ARTICLE_GET_ID_FAILURE";
//article edit
export const ARTICLE_EDIT = "ARTICLE_EDIT";
export const ARTICLE_EDIT_REQUEST = "ARTICLE_EDIT_REQUEST";
export const ARTICLE_EDIT_SUCCESS = 'ARTICLE_EDIT_SUCCESS';
export const ARTICLE_EDIT_FAILURE = "ARTICLE_EDIT_FAILURE";